### ISSUE TITLE
YAXLib maintenance

### ISSUE THREAD

**Issue by sinairv** [YAXLib/YAXLib#107]
Hello all, especially @304NotModified, @axunonb, @notheotherben, and @NKnusperer.

I've been busy for quite a while with other aspects of life, and couldn't pay enough attention to YAXLib as much as it deserves. I can see in some messages that you have been quite patience with it. Thanks and apologies.

I was wondering if you're interested in maintaining the library, including reviewing PRs, looking at open issues, build failures, and updating the nuget packages. 

If yes, I'd like to hear your suggestions too. I'll give necessary access to those who are interested.

I have to be honest here, that it would be extremely unlikely for me to be able to spend more time on it.

Please let me know what you think and what you suggest.

**Comment by 304NotModified** [comment]
Kudos for starting this discussion 👍 

Unfortunately I have to pass. I'm already not spending enough time to open source IMO and also I don't work anymore where this library is being used.

**Comment by axunonb** [comment]
Of course, it's always about what you spend your time on.

I still consider YAXLib an excellent library (and most feature complete) for working with XML. But it loses practical value if current versions of .NET are not supported. That was my motivation for the last PR. For NET 5.0, there are some unit tests that fail. That fix is still ahead (assuming it can be accomplished within reasonable limits of code changes and time).

Regarding YAXLib, I could offer to finish and release 2 next versions: One for NetStandard2.x, the next for NET5.0. Depending on what @notheotherben and @NKnusperer say about further collaboration on this repo, we can see how to proceed afterwards. The "lonely maintainer" isn't what I prefer. @sinairv: If you agree so far, I would be grateful for necessary access in order to proceed with the tasks mentioned.

**Comment by NKnusperer** [comment]
Thank your for open this discussion @sinairv.
I'd love to see a joint effort to bring this library back to life.
@axunonb we currently have a fork at [MhpSoftware/YAXLib.Redux](https://github.com/MhpSoftware/YAXLib.Redux) which has retargeted YAXLib to `netstandard2.0` with all testing passing und Windows and Linux under .NET 5, so this has already been resolved.

Maybe it is a good idea to move this project to a dedicated YAXLib GitHub organization for further development?

**Comment by axunonb** [comment]
@NKnusperer:
> I'd love to see a joint effort to bring this library back to life.

Highly appreciated

> we currently have a fork at MhpSoftware/YAXLib.Redux which has retargeted YAXLib 

Ahhhh, knowing this would have saved me quite a bit of time. Just completed the same [with another PR](https://github.com/sinairv/YAXLib/pull/108) a minute ago. Now using SemVer and SourceLink.

> dedicated YAXLib GitHub organization

Sure, I didn't have this in mind before. Happy to join.

**Comment by 304NotModified** [comment]
If someone need help and the integration part (AppVeyor, Codecov, NuGet), I would be happy to help with that (as it seems it's broken now). Please add me to the GitHub organization and would be nice if the org has the needed AppVeyor/CodeCov/NuGet rights.

**Comment by axunonb** [comment]
@304NotModified: Julian, I was really hoping for this statement. Great!

**Comment by 304NotModified** [comment]
PS: Working on the AppVeyor build issue

**Comment by 304NotModified** [comment]
#109 should fix it

**Comment by sinairv** [comment]
Thank you all. I appreciate all your helps. 
As you suggested @NKnusperer I just created a new organisation. You should get an invitation email shortly. 
Next I will start moving the repository to the organisation. I hope you all agree, and if you have done this before and there are tips and tricks that I must be aware of please let me know.

**Comment by 304NotModified** [comment]
It's pretty straightforward, just use the transfer ownership button on GitHub (repo settings)

It works pretty cool and github creates an intern redirect. AFAIK there is also no need to update existing remote urls :)

**Comment by sinairv** [comment]
Thank you. I just transferred the repository to `YAXLib/YAXLib`. Please let me know if there's any issues. I think you should be able to approve PRs and do anything else as well. 

I now need to give you access to nuget, and for that I need to add your email addresses to nuget portal. Since this thread is public, could you please send me an email and let me know what's your preferred email address to access nuget?
My email should be visible in my profile, if not it's <my-firstname>.<my-lastname>@gmail.com

**Comment by 304NotModified** [comment]
There is a private chat nowadays in GitHub.  It's under the organization :)

**Comment by axunonb** [comment]
> 
> 
> If someone need help and the integration part (AppVeyor, Codecov, NuGet), I would be happy to help with that (as it seems it's broken now). Please add me to the GitHub organization and would be nice if the org has the needed AppVeyor/CodeCov/NuGet rights.

So, finally AppVeyor is back on stage. Couldn't reproduce how come, but according to the GitHub docs, the 401 response may also come from too many requests in a short time. Then GitHub blocks further requests for "a short time". Anyway, it works again now. @304NotModified: Just added you to YAXLib org

**Comment by 304NotModified** [comment]
> So, finally AppVeyor is back on stage\

It's still not working correctly and it's also not forced yet on PRs. I've created #113  for this.

**Comment by sinairv** [comment]
Thank you guys, appreciate all your work.
I added @axunonb to AppVeyor and Nuget. 

@304NotModified and @NKnusperer please let me know if you also want to be added to AppVeyor and Nuget too.

Thanks again,
Sina

**Comment by 304NotModified** [comment]
Yes please AppVeyor and NuGet. For both you could setup teams AFAIK.

**Comment by 304NotModified** [comment]
And codecov if possible please, so I could fix that integration as well

**Comment by sinairv** [comment]
Great, could you please email me and send me the email address you use for AppVeyor as well as your nuget user name?

**Comment by sinairv** [comment]
@304NotModified I can see you're already added to CodeCov. Probably this is something you originally set up.

**Comment by axunonb** [comment]
Continued with #116
