### ISSUE TITLE
YAXLib vNext

### ISSUE THREAD

**Issue by axunonb** [YAXLib/YAXLib#116]
Now we have moved YAXLib to a new organization, and I'm thankful to see you all on board.
Should we think about how to go on? Here are some items we could discuss.

### YAXLib vNext

* [YAXLib.Redux](https://github.com/MhpSoftware/YAXLib.Redux) is 5 releases ahead of this repo. Would it make sense to use it as the base for further development?
* Which other features should become part of vNext? @sinairv already mentioned some ideas for a v3, which would also introduce breaking changes in terms of namespace and class names (like changing `YAXLib` to just `Yax`)
* How to deal with open issues? (Some might be covered in [YAXLib.Redux](https://github.com/MhpSoftware/YAXLib.Redux)?)
* [YAXLib.Redux](https://github.com/MhpSoftware/YAXLib.Redux) is explicitly targeting Linux. Should we go for Travis CI beside AppVeyor CI?
* Should we stick to Codecov CI?

### Team

* Would it make sense to assign certain main responsibilities in the team, like:
  * Further development path
  * managing issues
  * handling pull requests
  * keep the docs up-to-date
* Repo access rights? Currently @sinairv is owner, @NKnusperer, @304NotModified are admin, @axunonb is maintainer.

### Others

Anything else which comes to your mind?

I'm curious about your opinions.

**Comment by sinairv** [comment]
Thanks for this @axunonb. With regards to my earlier ideas, feel free to reassess them based on value vs effort. For example these days when I see the word `YAXLib` I wish I named it simply `Yax` or something else from the beginning. But, now I wonder, is it really worth the effort of renaming YAXLib to Yax. Is Yax really that much better? Not quite sure. So I suggest you to review all my earlier suggestions in a new pragmatic light. But up to you. As I said earlier, I may not be able to contribute actively (with tons of apologies in advance).

Great job with `YAXLib.Redux` too @NKnusperer. As much as I see value in having the two repositories merged, at the same time I don't want to be taken in the wrong way by this suggestion. If you have other plans in mind, @NKnusperer, that you think will not be met by the YAXLib main repository, I personally have nothing against keeping YAXLib.Redux separate.

**Comment by NKnusperer** [comment]
Hi everyone, `YAXLib.Redux` was born because we are currently in the process of making one of our products work under Linux.
`YAXLib` has been the backbone for XML serialization since day 0 and backwards compatibility is important, so it was only logical to continue with this lib. At the moment it does not contain any special code for this, it is just a cleanup of the existing code base  targeting `netstandard2.0`. It exist only for the purpose of being able to make changes if required.
What has been changes is:
- Removed most code from `ReflectionBridgeExtensions.cs` because those APIs are now part of `netstandard2.0` (see #104)
- Minor changes to the test suite to make everything pass under both Linux and Windows
- Updated dependencies for unit test project
- Completely migrated to the `dotnet` toolchain, e.g. NuGet packages can be published via `dotnet pack`
- Ported the `DemoApplication` to a .NET 5 Windows Forms app
- Removed no longer required files from the repository like `.nuget`, `packages` and `Key`.

I think that using this as a base for the YAXLib organization might be a good idea because this as clean as you can get without breaking anything.

On of the big challenges I see for now is to make serialized objects work under cross platform conditions.
I think that this is currently not possible because of an implementation quirk in .Net Core where what is known as `mscorlib` under the .Net Framework has been moved to `System.Private.CoreLib`. You can see this reflected in the test suite here:
https://github.com/YAXLib/YAXLib/blob/fb1c585c83f15b52a56ee8b9a9ef272a7aee5b63/YAXLibTests/SerializationTest.cs#L455

It should be possible to serialize an object under Windows and deserialize in under Linux and vice-versa.

**Comment by sinairv** [comment]
@NKnusperer Thanks for the detailed explanations. In that case I also agree with you to use merge `YAXLib.Redux` to the main repository. Having said that, I'm not sure how much of it will have conflict with the recent changes in which @axunonb also kindly added support for .NET 5.

**Comment by 304NotModified** [comment]
> * [YAXLib.Redux](https://github.com/MhpSoftware/YAXLib.Redux) is explicitly targeting Linux. Should we go for Travis CI beside AppVeyor CI?

Travis isn't really working well these days for open source. It was always already unsupported/experimental for .NET

Would recommend Azure Devops (ADO) these days. Maybe move everything to ADO. Its free, has 10 parallel jobs (AppVeyor only 1) and could run under Windows, Mac OS and Ubuntu

**Comment by 304NotModified** [comment]
Hey guys, there is a discussion feature in Github there days

Maybe that easier to use then an issue. 

Could you all see / post here? https://github.com/orgs/YAXLib/teams/maintainers/discussions

**Comment by axunonb** [comment]
> Would recommend Azure Devops (ADO) these days. Maybe move everything to ADO. Its free, has 10 parallel jobs (AppVeyor only 1) and could run under Windows, Mac OS and Ubuntu. Downside of ADO (compared to AppVeyor) is the starting time and the nuget restore - AppVeyor is on both faster.

I've never had a closer look at ADO. Sounds interesting, and speed is not of so big importance for this repo, is it? 
> > Should we stick to Codecov CI?
> 
> If we fully move to ADO, maybe also SonarCloud instead of codecov. CodeCov + AppVeyor is a nice fit, but with ADO it's easier (and better) to fix SonarCloud

Would be good to setup a test environment. @304NotModified Could you help with this?

**Comment by axunonb** [comment]
> I think that using this as a base for the YAXLib organization might be a good idea

Actually, we need a starting point to move on. I went through the diffs of YAXLib/YAXLib and MhpSoftware/YAXLib.Redux and my conclusion was to take over the solid MhpSoftware/YAXLib.Redux code base were the best solution.
@NKnusperer, @304NotModified: Let's go for that. Please include [this version of `appveyor.yml`](https://github.com/YAXLib/YAXLib/blob/f59b7f3c3083a3d7ca9adcdecab42ceba3e4f1c4/appveyor.yml) because of CI integration.

Next steps:
* Remove obsolete branch `Normalize-Line-Endings`
* @NKnusperer, @304NotModified: Should branch `Crossplatform-Compatibility` then be merged into the new codebase? Please review and advise.
* All this should end in a new release - agree?

**Comment by 304NotModified** [comment]
> Should branch Crossplatform-Compatibility then be merged into the new codebase? Please review and advise.

I guess it would be nice if this is done after the linux build has been setup on the CI?

**Comment by axunonb** [comment]
> I guess it would be nice if this is done after the linux build has been setup on the CI?

Local linux tests succeed, and actually it's rather cross-framework than cross-platform, but yes, why not.

**Comment by 304NotModified** [comment]
> Local linux tests succeed, and actually it's rather cross-framework than cross-platform, but yes, why not.

Ah OK, well if there is no need it isn't. I was under the impression linux build was needed because of 

> YAXLib.Redux is explicitly targeting Linux. Should we go for Travis CI beside AppVeyor CI?


Anyway, tests are failing on Linux, looks like a newline issue: https://ci.appveyor.com/project/SinaIravanian/yaxlib/builds/38009412/job/gn2r5soe0oivsbh8

**Comment by axunonb** [comment]
> Anyway, tests are failing on Linux, looks like a newline issue

Exactly. While windows requires
```
init:
  - git config --global core.autocrlf true
```
Linux expects
```
init:
  - git config --global core.autocrlf input
```

**Comment by axunonb** [comment]
> Should we go for Travis CI

Azure DevOps would have been very nice, but takes a bit more time maybe to get it running.
Travis CI can give us Ubuntu, and it is not a decision for ever ;-)

**Comment by 304NotModified** [comment]
Yes, well AppVeyor could give Ubuntu too :)

**Comment by axunonb** [comment]
> Yes, well AppVeyor could give Ubuntu too :)

If you'd like to try, remember that master doesn't have git LF normalized line endings yet. Use branch Normalize-Line-Endings, otherwise you'll get 103 tests failing.

**Comment by 304NotModified** [comment]
> If you'd like to try,

See here https://github.com/YAXLib/YAXLib/pull/119

> Use branch Normalize-Line-Endings, otherwise you'll get 103 tests failing.

Ah missed that! Updated https://github.com/YAXLib/YAXLib/pull/119

**Comment by 304NotModified** [comment]
> * All this should end in a new release - agree?

Please before releasing, do a pre-release to nuget :)  (guess it should be also 3.0)

**Comment by NKnusperer** [comment]
@axunonb see #120 for my merge of YAXLib.Redux.

**Comment by NKnusperer** [comment]
+1 for Azure DevOps simply because I use it daily on a professional basis :)

**Comment by axunonb** [comment]
All topics covered
