### ISSUE TITLE
Remove YAX prefix from classes and namespace

### ISSUE THREAD

**Issue by sinairv** [YAXLib/YAXLib#13]
- remove the redundant `YAX` prefix from every part of API.
- Introduce generic methods wherever possible, instead of passing around `System.Type` objects.
- The namespaces and other names could be renamed from `YAX...` to `Yax...`

**Comment by axunonb** [comment]
@NKnusperer @304NotModified 
I mean, YAX... is awkward to type and not following conventions. But it's also not just as simple as "removing the YAX prefix", like @asbjornu pointed out correctly.
Still: If we don't include the renaming of classes in v3, we should close the issue after 9 years.

**Comment by NKnusperer** [comment]
Personally, typing `YAX` is no issue and it makes every type name unique by default, which is a nice feature.
I would opt to close this issue too.
