### ISSUE TITLE
Reduce Cyclomatic Complexity

### ISSUE THREAD

**Issue by sinairv** [YAXLib/YAXLib#14]
- The source code is rather structured than object oriented. Many `if` branches can be prevented with a better object oriented design and polymorphism.
- Some methods (esp in `YAXSerializer`) class are excessively long
- Some naming conventions are Hungarian. Casing for static and private objects and methods do not seem proper. ReSharper default conventions seem to be OK.

**Comment by 304NotModified** [comment]
Is there a version 3 planned?

I found it very useful to check the code complexity of a method. see [Cyclomatic Complexity Resharper plugin](https://resharper-plugins.jetbrains.com/packages/PowerToys.CyclomaticComplexity/). Some methods have now +100 in code complexity. (the default threshold is 20)

**Comment by sinairv** [comment]
Absolutely agree with the Cyclomatic Complexity issues stated above, and that was originally the reason I logged this issue.

Given the relatively small number of people using the library and other available options in the .NET Framework, I was thinking it may not be worth investing more time and energy developing v3. Do you have any plans using it for NLog or somewhere else?

**Comment by acvanzant** [comment]
I like it just how it is. Wonderful library. [NIEM](https://www.niem.gov/Pages/default.aspx) is a headache of a thing to deal with and this is excellent, so far, at removing the unneeded complexity.

**Comment by axunonb** [comment]
Candidates for improving [Cyclomatic Complexity](https://en.wikipedia.org/wiki/Cyclomatic_complexity):

| Method | Cycl. Compl. |
| :---- | ----: |
| YAXSerializer.SerializeBase(object obj, XName className) | 70 |
| YAXSerializer.MakeDictionaryElement(XElement insertionLocation, XName elementName, object elementValue,            YAXDictionaryAttribute dicAttrInst, YAXCollectionAttribute collectionAttrInst, bool dontSerializeNull) | 33 |
| YAXSerializer.DeserializeBase(XElement baseElement) | 67 |
| YAXSerializer.RetrieveElementValue(object o, MemberWrapper member, string elemValue, XElement xelemValue) | 33 |
| YAXSerializer.DeserializeCollectionValue(Type colType, XElement xelemValue, XName memberAlias,            YAXCollectionAttribute colAttrInstance) | 59 |
| YAXSerialzer.DeserializeTaggedDictionaryValue(XElement xelemValue, XName alias, Type type, YAXCollectionAttribute colAttributeInstance, YAXDictionaryAttribute dicAttrInstance) | 25 |

**Comment by axunonb** [comment]
Some efforts are made on the way to v4
