### ISSUE TITLE
Bad naming: Value -> Content

### ISSUE THREAD

**Issue by sinairv** [YAXLib/YAXLib#15]
`SerializeAsValue` and the like, should be renamed to `SerializeAsContent`.

**Comment by 304NotModified** [comment]
Agree, but prefer to keep both and mark one as obsolete (if it's not making to much code duplication)

**Comment by axunonb** [comment]
@304NotModified We have `YAXValueForClassAttribute` and `YAXValueForAttribute`. Was this meant to change to `YAXContentForClassAttribute` and `YAXContentForAttribute`? Okay for the first, not sure for the latter.
(SerializeAsValue doesn't exist)

**Comment by 304NotModified** [comment]
Funny, I was also looking a this today. I really don't know. It has been a few years ago. 



> Okay for the first, not sure for the latter.

Will think about this, maybe we should check with the XML specs / other XML serializers for the common term?

**Comment by axunonb** [comment]
Low relevance and not worth a breaking change.
