### ISSUE TITLE
YAXSerializer shouldn't change its SerializerOptions

### ISSUE THREAD

**Issue by axunonb** [YAXLib/YAXLib#153]
After running this test
https://github.com/YAXLib/YAXLib/blob/29d4d763e3b537fc837b48044d7539e502e1f514/YAXLibTests/SerializationTest.cs#L2254-L2257
`ser.MaxRecursion` will be changed to `1`,
while it is expected to keep the initial setting of `10`.
This is caused by `YAXSerializer` here
https://github.com/YAXLib/YAXLib/blob/29d4d763e3b537fc837b48044d7539e502e1f514/YAXLib/YAXSerializer.cs#L2493-L2497

ReSharper says, this is the only occurrence where `SerializerOptions` members art `set`.

Todo: 
* Change to not using `SerializerOptions` directly.
* Consider using C# 9 `record`s instead of a `class`. See [Use Records with NetStandard 2](https://bartwullems.blogspot.com/2021/01/c-9use-record-types-in-net-standard-20.html).

**Comment by 304NotModified** [comment]
Another option is to clone the options

**Comment by axunonb** [comment]
... yes, and restore to the original options after serialization and deserialization, in case we re-use the same instance of `YAXSerializer`.

**Comment by 304NotModified** [comment]
After clone you normally don't restore things? They are separated (for a reason)

**Comment by axunonb** [comment]
Well,
`Options.MaxRecursion = Options.MaxRecursion == 0 ? 0 : Options.MaxRecursion - 1; `
will still decrement `Options.MaxRecursion` in the cloned options and re-use the cloned `Options`next time we serialize with the same instance of `YAXSerializer`. It's so well separated, is it?

**Comment by 304NotModified** [comment]
I think there is another issue here, the MaxRecursion should not be used as "state" or "context". It should be a separate context class/parameter. Then there is no need to alter the MaxRecursion ?

**Comment by axunonb** [comment]
Fully agree, that's the actual reason of this bug: using a setting variable as an ever changing state.
