### ISSUE TITLE
Release V3 RTM

### ISSUE THREAD

**Issue by 304NotModified** [YAXLib/YAXLib#157]
I propose within 1-2 weeks if there are no issues :)

**Comment by 304NotModified** [comment]
@YAXLib/maintainers good to go? :)

**Comment by axunonb** [comment]
The number of installations is not as I hoped for, but yes, good to go.

With regard to open feature requests: Should we go in advance or wait until the number of installations increases significantly?

**Comment by 304NotModified** [comment]
I think the latter

**Comment by 304NotModified** [comment]
it's live! 

https://www.nuget.org/packages/YAXLib/3.0.0

Also created a GitHub release: https://github.com/YAXLib/YAXLib/releases/tag/v3.0

**Comment by axunonb** [comment]
Great, thanks a lot!
