### ISSUE TITLE
Add the specific reason causing a YAXException to the description

### ISSUE THREAD

**Issue by Marvin-Brouwer** [YAXLib/YAXLib#164]
**Is your feature request related to a problem? Please describe.**
I am getting the following error: "The generic argument of the class and the member type do not match"
But I have a hard time figuring out where.

**Describe the solution you'd like**
I'd like either both or one of:
- Type.Name of both the target type and the type of the ICustomSerializer<> generic in the exception message
- Properties on the exception with the full type name of previously mentioned types.

Preferably both.

**Describe alternatives you've considered**
None

**Comment by axunonb** [comment]
True, these error messages should become more specific.
Currently we have 5 occurrences of `new YAXException`.
* https://github.com/YAXLib/YAXLib/blob/438a1ae0277b2744c4cb7d1cf3e371332c75600f/YAXLib/EnumWrapper.cs#L54
* https://github.com/YAXLib/YAXLib/blob/438a1ae0277b2744c4cb7d1cf3e371332c75600f/YAXLib/MemberWrapper.cs#L724-L725
* https://github.com/YAXLib/YAXLib/blob/438a1ae0277b2744c4cb7d1cf3e371332c75600f/YAXLib/MemberWrapper.cs#L727
* https://github.com/YAXLib/YAXLib/blob/438a1ae0277b2744c4cb7d1cf3e371332c75600f/YAXLib/UdtWrapper.cs#L424-425
* https://github.com/YAXLib/YAXLib/blob/438a1ae0277b2744c4cb7d1cf3e371332c75600f/YAXLib/UdtWrapper.cs#L428
Other exceptions might lack of specific error causes, as well.

**Comment by Marvin-Brouwer** [comment]
Great,

Might I suggest having specific Exceptions derived from the YAXExceptions?
Something like this:
```cs 
[Serializable]
public class YAXEnumSerializationException : YaxException 
{
  public Type EnumType { get; }
  public string Alias { get; }

  public YAXEnumSerializationException(Type enumType, string alias) : base($ "Enum alias '{alias}' already exists on {enumType.Name}") {
     EnumType = enumType;
     Alias = Alias;
  }
}
```
```cs 
[Serializable]
public class YAXCustomSerializerException : YaxException 
{
  public PropertyInfo Property { get; }
  public Type CustomSerializerType { get; }

  public YAXCustomSerializerException (PropertyInfo property, Type customSerializerType) 
    : base($"The provided custom serialization type '{customSerializerType.GetGenericType().Name}' is not derived from the proper interface") {
     Property = property;
     CustomSerializerType = customSerializerType;
  }
}
```
etc.

It's not particularly necessary but I find it helps a lot with quickly figuring what happened.

**Comment by axunonb** [comment]
>
> but I find it helps a lot with quickly figuring what happened

That's right. To throw different exceptions would be considered as a breaking change. Options so far:
* Include the reason of the exception into the description text (no breaking change)
* Create new exception types (breaking change)
* Extend the `YaxException` with an inner exception(s) property with more details (no breaking change)

@304NotModified Your preference (or better alternative)?

**Comment by Marvin-Brouwer** [comment]
I'm not sure I would consider it breaking if the new exceptions just inherits YAXException.
That way code catching YAXException will still catch.

**Comment by 304NotModified** [comment]
> I'm not sure I would consider it breaking if the new exceptions just inherits YAXException.
That way code catching YAXException will still catch

I don't think it's a breaking change! So good idea!
