### ISSUE TITLE
Support ICustomSerializer<TType> on properties of TType?

### ISSUE THREAD

**Issue by Marvin-Brouwer** [YAXLib/YAXLib#165]
**Is your feature request related to a problem? Please describe.**
Well, currently I need to duplicate all my ICustomSerialzers because I can't implement both in one class, which causes an error, and we usually have the need for custom serializers for structures like DateTime which is a struct so we can have nullables and non-nullables here.
For example:
StartDate vs EndDate, usually a start date is mandatory and end date isn't in a lot of use-cases.

**Describe the solution you'd like**
I'd like the YAXSerializer to just understand that a Nullable Date time can be handled with ICustomSerialzer<DateTime> when it has value.
And that way if it is null, it can fall back to the configured null behavior instead of relying on the ICustomSerializer to handle that.

**Describe alternatives you've considered**
I have them duplicated now.

**Comment by axunonb** [comment]
@Marvin-Brouwer 

There will be `SerializationContext` in v4, which contains `SerializerOptions` as a property.
This way, an `ICustomSerializer` is able to respect this setting and de/serialize accordingly.

Also, if a property has a `YAXCustomSerializer` and a `YAXDontSerializeIfNull` attribute, the custom serializer won't be invoked for `null` values.

Would this resolve your feature request?
Or would you expect on top, that the `SerializerOptions` set for the `YAXSerializer` should apply for `ICustomSerializer`s, too? Would mean a breaking change.

**Comment by Marvin-Brouwer** [comment]
@axunonb.

The only thing I want is not to duplicate serializers to handle nulls.
So, yes, your solution would resolve my feature request.

**Comment by axunonb** [comment]
Great, thanks, so this will be the case in v4.

**Comment by axunonb** [comment]
Resolved with release [v4.0.0](https://github.com/YAXLib/YAXLib/releases/tag/v4.0.0)
