### ISSUE TITLE
String appears as an empty element even when set to null

### ISSUE THREAD

**Issue by Nikey646** [YAXLib/YAXLib#175]
**YAXLib version**: 3.0.1

**Framework version**:  .Net ~~5~~ 6

- What is the current result? 
String field set as null is serialized as an empty element even with `YAXLib.YAXSerializer.Options.SerializationOptions = YAXSerializationOptions.DontSerializeNullObjects;` irrelevant if string is empty or explicitly set to null.

- What is the expected result?
Element not appearing in the result.

- Please post full exception details if applicable (message, stacktrace, inner exceptions)
N/A

- Did you find a workaround? yes/no
no

- Is there a version in which it worked? 
N/A

- Can you help us by writing an unit test?
Sorry, not very good at writing tests.

**Comment by axunonb** [comment]
Please provide a working code sample as we can't reproduce this behavior.

**Comment by Nikey646** [comment]
A [.Net Fiddle](https://dotnetfiddle.net/jBi4qm) that shows the result as well.

The first result is kind of as expected.

The second result however, I'm not sure if I'm using the Serializer.Options incorrectly, but it shouldn't be appearing from my understanding?

Expected output for the second one should be 
```xml
<MyObj>
</MyObj>
```
or
```xml
<MyObj />
```

**Comment by Nikey646** [comment]
> Please provide a working code sample as we can't reproduce this behavior. See #174 for a working example regarding serialization.

Upon comparing the difference between the code I was using and the code provided in #174, setting the `serializer.Options.SerializationOptions` after the creation of the serializer while allowed (Has a public setter), it's not respected.

When creating a new `SerializerOptions` in the constructor, it works as expected.

**Comment by Nikey646** [comment]
> Changing the `SerializerOptions` after creating the instance of `YAXSerializer` has no effect. This, however, will work:
> 
> ```cs
> [Test]
> public void DontSerializeNullObjects_Test()
> {
>     var serializer = new YAXSerializer(typeof(MyObj), new SerializerOptions {SerializationOptions = YAXSerializationOptions.DontSerializeNullObjects });
>     //serializer.Options.SerializationOptions = YAXSerializationOptions.DontSerializeNullObjects;
> 
>     var empty = new MyObj { MyValue = "" };
>     var nullVal = new MyObj { MyValue = null };
> 
>     var emptyRes = serializer.Serialize(empty);
>     var nullRes = serializer.Serialize(nullVal);
> 
>     emptyRes.Should().Contain("MyValue");
>     nullRes.Should().NotContain("MyValue");
> }
> ```
> 
> That`s why we're asking for a working code sample ;-)

I didn't realize that it would have been because applying the settings after creating the serializer would be the issue, hence why I didn't provide a code example.

In 4.x, or even potentially risking a breaking change in 3.x, and making the setters private for those? And only accepting the values from the constructor, with all arguments being optional?

**Comment by axunonb** [comment]
> When creating a new `SerializerOptions` in the constructor, it works as expected.

[Exactly](https://github.com/YAXLib/YAXLib/issues/176#issuecomment-1117333757)
