### ISSUE TITLE
How to transform property name during serialization

### ISSUE THREAD

**Issue by Nikey646** [YAXLib/YAXLib#176]
**Is your feature request related to a problem? Please describe.**
Serializing to an odd xml format that is out of my control. It is very fiddly, so ideally the attributes and element names would be all lowercase to conform. This would require apply a `YAXSerializeAs(...)` attribute on every property / class.

**Describe the solution you'd like**
Having some sort of name transformer provided in the options with a to / from method, or provided via an attribute and applied 'downwards'. Defaults like camelCase, snake_case, etc could be provided.

**Describe alternatives you've considered**
N/A Refer to problem.

**Comment by axunonb** [comment]
> This would require apply a `YAXSerializeAs(...)` attribute on every property / class.

For this task you could implement a class level `YAXCustomSerializer`.
See our tests for examples: https://github.com/YAXLib/YAXLib/blob/master/YAXLibTests/CustomSerializerTests.cs

**Comment by Nikey646** [comment]
> > This would require apply a `YAXSerializeAs(...)` attribute on every property / class.
> 
> For this task you could implement a class level `YAXCustomSerializer`. See our tests for examples: https://github.com/YAXLib/YAXLib/blob/master/YAXLibTests/CustomSerializerTests.cs

Would it not be more efficient to be able to control the naming convention from both the `SerializerOptions`, and the `YAXCustomSerializer` attribute? Or is the project trying to avoid too many options to keep complexity low?

Thank you for the response none the less :)

**Comment by axunonb** [comment]
@Nikey646 If it was possible to initiate the attribute like `YAXSerializeAs(typeof(MyNameTransformer))`, where the `MyNameTransformer` class would have a method e.g. `string GetAlias(string originalName)` - would this help in your case?
(Working with only 1 transformer, you would still have to decorate all classes and their members with `YAXSerializeAs(typeof(MyNameTransformer))`).

**Comment by Nikey646** [comment]
> @Nikey646 If it was possible to initiate the attribute like `YAXSerializeAs(typeof(MyNameTransformer))`, where the `MyNameTransformer` class would have a method e.g. `string GetAlias(string originalName)` - would this help in your case? (Working with only 1 transformer, you would still have to decorate all classes and their members with `YAXSerializeAs(typeof(MyNameTransformer))`).

I'm trying to avoid decorating every class and member with an attribute as the main objective.

Ideally, decorating the class would be the most that needs to be done, and the members would 'look up' to find the name transformer.

> Without more contributors to the YAXLib project I'm afraid we won't be able to follow up.

That is understandable :)

**Comment by axunonb** [comment]
> I'm trying to avoid decorating every class and member with an attribute as the main objective.

Sure, `YAXSerializeAs(typeof(MyNameTransformer))` would be easy to implement, but it's only half the way.
