### ISSUE TITLE
Dictionary serialization incorrect when publishing to single file

### ISSUE THREAD

**Issue by prettyv** [YAXLib/YAXLib#179]
**YAXLib version**: 3.0.1
**Framework version**:  net6.0
**.NET SDK**: 6.0.2.sdk102
**Operating system**: Arch Linux

### What is the current result?

The following minimal example code exhibits the problematic behaviour:
```csharp
namespace YAXTest;

public class YAXDictionaryTest
{
    public Dictionary<string, string> testDict { get; set; } = new();
}

public static class Program {
    public static int Main(string[] args)
    {
        YAXLib.YAXSerializer serializer = new(typeof(YAXDictionaryTest));
        serializer.SerializeToFile(new YAXDictionaryTest(), "serializationtest.xml");

        return 0;
    }
}
```
using a minimal project file with single file publishing enabled:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="YAXLib" Version="3.0.1" />
  </ItemGroup>

</Project>
```

Cross-publishing this for Windows from my Arch Linux installation with `dotnet publish -r win-x64 --self-contained` and executing with `wine` or on a native Windows machine produces the following serialized XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<YAXDictionaryTest xmlns:yaxlib="http://www.sinairv.com/yaxlib/">
  <testDict>
    <Comparer yaxlib:realtype="System.Collections.Generic.GenericEqualityComparer`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]" />
    <Count>0</Count>
    <Keys>
      <Count>0</Count>
    </Keys>
    <Values>
      <Count>0</Count>
    </Values>
  </testDict>
</YAXDictionaryTest>
```

### What is the expected result?
Without single file publishing enabled the output is as expected:
```xml
<?xml version="1.0" encoding="utf-8"?>
<YAXDictionaryTest>
  <testDict />
</YAXDictionaryTest>
```

Publishing for the default local `linux-x64` target works correctly independent of whether single file publishing is active or not.

### Did you find a workaround? yes/no
Not so far, but my experience with .NET is limited. I was looking for a way to exclude package reference assemblies from single file publishing but got the impression that this is unfortunately not supported.

### Is there a version in which it worked? 
Haven't tested with earlier versions yet.

**Comment by axunonb** [comment]
Hi,
That sounds really weird. The v3.0.1 unit tests under Windows and Linux were successful and I don't have your environment at hand.
However, this effect can be reproduced on Windows and Linux, if [`ReflectionUtils.IsPartOfNetFx(MemberInfo memberInfo)`](https://github.com/YAXLib/YAXLib/blob/ba71124b87a0fb6582a4823b54d22e7ec00f596e/YAXLib/ReflectionUtils.cs#L753) retunrs false.
Could you please check the value of any system type's module name, like `typeof(string).Module.Name`. It's expected to be `System.Private.CoreLib.dll` for `netstandard2.0`.

**Comment by prettyv** [comment]
Interesting, `typeof(string).Module.Name` returns `<Unknown>` when publishing as a single file app. This is also true when publishing for a linux target, seems like I might not have tested what I  thought to have tested when reporting.

I get this warning when publishing for a target with a clean cache:
```
warning IL3002: Using member 'System.Reflection.Module.Name' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. Returns <Unknown> for modules with no file path.
```

I don't quite know what to make of this yet.

**Comment by axunonb** [comment]
> warning IL3002: Using member 'System.Reflection.Module.Name' which has 'RequiresAssemblyFilesAttribute' can break functionality when embedded in a single-file app. Returns <Unknown> for modules with no file path.

At least we know the reason for this issue. Btw: `System.Reflection.Module.Name` is used only at this place in *YAXLib*.

**Comment by prettyv** [comment]
I can't say I fully understand the context around the code in question, but as a minimal change wouldn't it be sufficient to change the logic from checking the `memberInfo.Module.Name` to `memberInfo.Assembly.GetName().Name`? That should give pretty much the same strings to test against, only without the `.dll` extension, if I'm understanding the code right.
