### ISSUE TITLE
Possible regression caused by PR #183

### ISSUE THREAD

**Issue by axunonb** [YAXLib/YAXLib#188]
`YAXSerializer<T>` does not contain `internal` properties (e.g. `RecursionCount`, `TypeNamespace` and others)

E.g. used in tests
https://github.com/YAXLib/YAXLib/blob/5a37f7fe33ed66ffe72f25205f7bdd32b44060eb/YAXLibTests/DeserializationTest.cs#L659

https://github.com/YAXLib/YAXLib/blob/5a37f7fe33ed66ffe72f25205f7bdd32b44060eb/YAXLibTests/SerializationTest.cs#L2397

**Comment by 304NotModified** [comment]
Link pr: #183

**Comment by 304NotModified** [comment]
Regression of which bug? Do you have some more info?

**Comment by 304NotModified** [comment]
Maybe we should rewrite the tests so they (also) use the generic version. We could do that genericly I guess. 

Ps to prevent regression bugs, add tests;)

**Comment by axunonb** [comment]
Regression was just my first thought, that's why "possible". But absolutely, test coverage should improve:
more and smaller units. One by one ;-)

**Comment by axunonb** [comment]
Btw. there are tests just serializing, where it was interesting to see, whether deserialization works, too.
Maybe put "Improving unit tests" to the project list?

**Comment by 304NotModified** [comment]
I could work on those tests so they run also for the generic version

**Comment by axunonb** [comment]
Just let me finish the "remove obsolete methods" before. Latest by Friday, I guess.

**Comment by 304NotModified** [comment]
ok!

**Comment by 304NotModified** [comment]
All tests run succesful for the generic version, so there is no bug. See #194
