### ISSUE TITLE
Extend caching and pooling for better performance

### ISSUE THREAD

**Issue by axunonb** [YAXLib/YAXLib#193]
* Implement cache for `MemberWrappers`
* Implement object pool pattern for child `YAXSerializer`s
* Rename `TypeWrappersPool` to `UdtWrapperCache` (that's what it actually is)
* Re-use a cached instance for `ICustomSerializer`s instead of invoking a new instance repetitively. This could also increase usability of custom serializers

**Comment by 304NotModified** [comment]
Cool stuff. But is there a max cache size? Or what happens if there is a memory shortage?

**Comment by 304NotModified** [comment]
Yes otherwise you could get  memory leaks or out of memory issues.

**Comment by axunonb** [comment]
Ah, yeah, didn't consider this. I'll take a deeper look. My first idea was a First-in/First-out when reaching max. size.
(Existing type cache is also implemented as simple dictionary.)

**Comment by axunonb** [comment]
Just ported https://github.com/NLog/NLog/blob/dev/src/NLog/Internal/Collections/MruCache.cs - looks good. I think I'm gonna go for that😉

**Comment by axunonb** [comment]
@304NotModified Just checked the number of recursions that happen across all unit tests and using method `YAXSerializer.NewInternalSerializer`
With every counted recursion, a new `YAXSerializer` is created and later discarded (set to `null`) in `FinalizeNewSerializer`.
A `YAXSerializerPool` might bring a gain in speed and less GC pressure, wouldn't it?
```
Group             Count
9 Recursions =   110168
8 Recursions =      326
7 Recursions =     2293
6 Recursions =      126
5 Recursions =      963
4 Recursions =       26
3 Recursions =       52
2 Recursions =      168
1 Recursion  =     1106

Total Count  =   115228
```

**Comment by axunonb** [comment]
Got it working with an `YAXSerializer` object pool.

Results are promising - about 6x faster with 6x less GC pressure compared to the current v4 branch:
```
|                    Method |    N |      Mean |    Error |   StdDev |     Gen 0 | Allocated |
|-------------------------- |----- |----------:|---------:|---------:|----------:|----------:|
| NoPool_NoWrapperCache_V4  |  500 |  83.19 ms | 0.941 ms | 0.834 ms | 4000.0000 |     35 MB |
| NoPool_NoWrapperCache_V4  | 1000 | 164.48 ms | 1.682 ms | 1.573 ms | 8000.0000 |     71 MB |
|-------------------------- |----- |----------:|---------:|---------:|----------:|----------:|
| With_Pool_WrapperCache    |  500 |  14.12 ms | 0.281 ms | 0.438 ms |         - |      6 MB |
| With_Pool_WrapperCache    | 1000 |  28.84 ms | 0.561 ms | 0.690 ms | 1000.0000 |     13 MB |
```
Cache and Pool both have limits in size now. Actually, the pool is rather small: only 12 items across all unit tests, but used with a high frequency.
