### ISSUE TITLE
Split IYAXSerializer<T> to IYAXSerializer<T> and IYAXDeserializer<T>

### ISSUE THREAD

**Issue by 304NotModified** [YAXLib/YAXLib#195]
Split IYAXSerializer<T> to IYAXSerializer<T> and IYAXDeserializer<T>

So we can make the interfaces (co/contra) variant. See https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/covariance-contravariance/

**Comment by 304NotModified** [comment]
@axunonb please your opinion on this

**Comment by 304NotModified** [comment]
See https://github.com/YAXLib/YAXLib/pull/196

**Comment by axunonb** [comment]
Hey, **very** cool! 
Must admit I never came across covariance and contravariance before, so I first had to understand what's behind ;-)  
"multi-state" in `IYAXMultiStateDeserializer` expresses what is called "multi-stage" in the docs. Is "multi-state" the right word?

**Comment by 304NotModified** [comment]
Oops thats a typo, it should be multistage indeed

**Comment by 304NotModified** [comment]
this isn't planned anymore

**Comment by axunonb** [comment]
Hm, I still like this...

**Comment by 304NotModified** [comment]
I think it needs a case why we need. Maybe its YAGNI.
