### ISSUE TITLE
How serialize a list as an attribute

### ISSUE THREAD

**Issue by Marvin-Brouwer** [YAXLib/YAXLib#201]
Hi,

I have a scenario where I have a key value pair.
I'd like to make that an attribute on an object but I don't know IF it should be on my object and I don't know how many might get added in the future hence the key value pair.
it's actually `List<(string attribute, string value)>` do you have an OOTB solution for that or do I need to write my own converter?

**Comment by axunonb** [comment]
Sorry, I'm afraid serializing `ValueTuple`s currently isn't implemented.
Besides that, I'm not sure whether this is what you're after:

```CSharp
public class SomeDemoClass
{
    public string Name { get; set; }
    
    [YAXCollection(YAXCollectionSerializationTypes.Serially, SeparateBy = ", ")]
    [YAXAttributeForClass]
    public List<string> AttributeValues { get; set; }

    public static SomeDemoClass GetSampleInstance()
    {
        var vt = new List<string>();
        vt.Add(("one|one-value"));
        vt.Add(("two|two-value"));
        vt.Add(("three|three-value"));
        vt.Add(("four|four-value"));
        var w = new SomeDemoClass
        {
            Name = "Some name",
            AttributeValues = vt
        };

        return w;
    }
}

var s = new YAXSerializer(typeof(SomeDemoClass));
var xml = s.Serialize(SomeDemoClass.GetSampleInstance());
```
This would serialize the list as an attribute of the containing class:

```Xml
<SomeDemoClass AttributeValues="one|one-value, two|two-value, three|three-value, four|four-value">
  <Name>Some name</Name>
</SomeDemoClass>
```

**Comment by Marvin-Brouwer** [comment]
I'm sorry, I should've added an example.

So what I'm trying to achieve is this:

```C#
public sealed class SomeModel {

    // Other props hidden for example
    public IReadonlyList<(string name, string value)> AdditionalAttributes {get;set;}
}
```
With this value:
```C#
var foo = new SomeModel { 
    AdditionalAttributes = {
        ("qux", "4"),
        ("quo", "20")
    }
};
```
And I want this to translate to:
```xml
<SomeModel qux="4" quo="20">
    <!-- properties and children hidden for example -->
</SomeModel>
```

I think I have a solution for this, I was mostly just wondering if there's an OOTB attribute available but I don't think so from scanning the repo.
I'll post my solution if I test it successfully. Otherwise, I'll just have to have a model with all the possible attributes and set the ones I don't need to null I guess.

**Comment by axunonb** [comment]
> ```
> <SomeModel qux="4" quo="20">
> ```

Thanks for the clarification.
So you don't want to place all the attributes from the list, but just the ones you need ;-)
Yes, I'd be interested in how you finally solved that, including the `ValueTuple`s.

**Comment by axunonb** [comment]
That's a smart idea `[YAXAttributeForClass, YAXCustomSerializer(typeof(AdditionalAttributesSerializer))]` and "almost" out-of-the-box 😉.  Thanks for sharing!

**Comment by axunonb** [comment]
**Todo:** Add @Marvin-Brouwer 's code to the samples of the Wiki.
