### ISSUE TITLE
Add YAXSerializationOptions.StripInvalidXmlChars

### ISSUE THREAD

**Issue by axunonb** [YAXLib/YAXLib#206]
> there should be way to just **remove** the illegal characters like \u0003

Agree. In it's simplest form all values would have to undergo a `RegEx.Replace` or maybe better stripped like
```cs
var input = "abc\u0003def";
var validXmlString = new string(input.Where(XmlConvert.IsXmlChar).ToArray())
```
If we're lucky, all values are anyway retrieved using `XMLUtils.ToXmlValue(this object? self, CultureInfo culture)` and the clean-up could be added there ;-)  Then, maybe we could introduce `YAXSerializationOptions.StripInvalidXmlChars` or alike.

**This is only required for serialization**, because `XDocument.Load(...)` is used for reading XML and it will throw on invalid characters anyway.

_Originally posted by @axunonb in https://github.com/YAXLib/YAXLib/issues/2#issuecomment-1227168202_

**Comment by axunonb** [comment]
@304NotModified 
`YAXSerializationOptions.StripInvalidXmlChars` will be included with the next PR. The effort and code changes were less than expected.

**Comment by 304NotModified** [comment]
fixed by https://github.com/YAXLib/YAXLib/pull/208?

**Comment by axunonb** [comment]
Yes, indeed
