### ISSUE TITLE
Structs are not serialized correctly

### ISSUE THREAD

**Issue by eocron** [YAXLib/YAXLib#214]
Structs are not serialized/deserialized correctly, for example specifying any Value (123,234,456) of:

```
    public struct XmlTestStruct
    {
        public int Value;
    }
```

will result to
```
<XmlTestModelFooBar>
  <Struct />
</XmlTestModelFooBar>
```

Problem seems because of Value is actually a Field, not a Property.

**Comment by 304NotModified** [comment]
What is the call and the used options?

Because:

> By default, YAXLib serializes only public properties of the type that is specified

See https://github.com/YAXLib/YAXLib/wiki#choosing-the-fields-to-be-serialized

**Comment by 304NotModified** [comment]
And are we talking about 3.0.1?

**Comment by axunonb** [comment]
Closed after missing feedback
