### ISSUE TITLE
Serializing an Exception Crashes the application (no exception thrown)

### ISSUE THREAD

**Issue by Vaccano** [YAXLib/YAXLib#22]
Make a project and run this:

void Main()
{
    try
    {
        int zero = 0;
        int result = 100 / zero;
    }
    catch (DivideByZeroException ex)
    {
        LogSaveException(ex);
    }
}

public void LogSaveException(object value)
{
    try
    {
        YAXSerializer serializer = new YAXSerializer(value.GetType());
        string loggedString = serializer.Serialize(value);
        Console.WriteLine(loggedString);
    }
    catch (Exception)
    {
        Console.WriteLine("Log Error", "Could Not Log object of type " + value.GetType().ToString());
    }
}

It will crash the app.  (Even though you are catching all exceptions.)

**Comment by 304NotModified** [comment]
This is also visible from the tests. It looks like Yaxlib is serializing every type in the appdomain.

**Comment by axunonb** [comment]
Duplicate to https://github.com/YAXLib/YAXLib/issues/62
Will follow-up there and close this issue.
