### ISSUE TITLE
Collection Deserialization with RecursiveWithNoContainingElement

### ISSUE THREAD

**Issue by Jonsen94** [YAXLib/YAXLib#250]
Hello,
I am currently trying to Serialize/Deserialize from C# to XML.

I think I ran into some problems regarding collection serialization especially when RecursiveWithNoContainingElement is set.

**YAXLib version**: 2.2.0

**Framework version**:  net8.0

- What is the current result? (Working source code to reproduce is highly appreciated)
Setup, the following classes:

``` C#
class TestClass
{
    [YAXCollection(YAXCollectionSerializationTypes.RecursiveWithNoContainingElement, EachElementName = "collection")]
    public IList<DataClass> Test { get; init; } = new List<DataClass>();
}

class DataClass
{
public string A {get; set;}
public string B {get; set;}
}
```
Test Code:
``` C#
public void Serialize(){
  var serializer = new YAXSerializer(typeof(TestClass));
  
  var tmp = new TestClass();
  tmp.Test.Add(new DataClass() {A = "A", B = "B"});
  tmp.Test.Add(new DataClass() {A = "C", B = "D"});
  
  using var stringWriter = new StringWriter();
  serializer.Serialize(tmp, stringWriter);
  
  var xml = stringWriter.ToString();
}
```

The resulting XML looks like expected:
``` XML
<TestClass>
  <Name>Dummy</Name>
  <collection>
    <A>A</A>
    <B>B</B>
  </collection>
  <collection>
    <A>C</A>
    <B>D</B>
  </collection>
</TestClass>
```

Parsing the XML back yields an exception:
`{"No elements with this name found: './A'."}`

- What is the expected result?
Expected result is to get back
- Please post full exception details if applicable (message, stacktrace, inner exceptions)
- Did you find a workaround? yes/no
I did not find a workaround but I think the problem is within  `Deserialization.cs` line 831-840.
There we decide if the collection is serially or recursively serialized.

In the GetRecursiveCollectionItems method we then assume (line 1098 - 1100) that each child element must be deserialized as the inner type of the collection. As we set "RecursiveWithNoContainingElement" earlier all child elements of this specific element has to be deserialized as a single instance of the inner type.

Please correct me if I am using any attribute wrong or if I'm missing something.

**Comment by Jonsen94** [comment]
Thank you for the fast response!

Seems like I missed something during my tests there.

It works with your version. Not sure how I missed that.

**Comment by axunonb** [comment]
@Jonsen94 
> YAXLib version: 2.2.0

Guess you meant v4.2.2, right?

**Comment by Jonsen94** [comment]
Yes, updated the initial post so people finding this issue wont be missguided.
