### ISSUE TITLE
Error by desiralize DateTime on german system

### ISSUE THREAD

**Issue by gitgordon** [YAXLib/YAXLib#35]
Hello,
by deserialize a DateTime object on a german windows the new DateTime is wrong (see example).

``` c#
DateTime date = new DateTime(2015, 7, 20);
YAXLib.YAXSerializer s = new YAXLib.YAXSerializer(typeof(DateTime));
string xml = s.Serialize(date);
Console.WriteLine(xml); // <DateTime>07/20/2015 00:00:00</DateTime>
object obj = s.Deserialize(xml);
Console.WriteLine(obj); // 01.01.0001 00:00:00
```

This is because the `ParseDateTimeTimeZoneSafe` method in the `StringUtils.cs` class does not use the `IFormatProvider` parameter. Instead of using:

``` c#
if (!DateTimeOffset.TryParse(str, out dto))
```

you must use:

``` c#
if (!DateTimeOffset.TryParse(str, formatProvider, System.Globalization.DateTimeStyles.None, out dto))
```

Thank you for fixing this issue.
Gordon

**Comment by diegobarbosa** [comment]
Is this fixed?

**Comment by 304NotModified** [comment]
I think not, but you could send a PR for it?

**Comment by diegobarbosa** [comment]
Is this fixed?

**Comment by axunonb** [comment]
Fixed with https://github.com/YAXLib/YAXLib/pull/58
