### ISSUE TITLE
Add option to serialize private members from base types

### ISSUE THREAD

**Issue by gitberni** [YAXLib/YAXLib#36]
If you serialize a class B that derives from A then the private fields of A are not serialized even if you apply the correct type attributes. The reason is in the `GetFieldsToBeSerialized(...)` method. GetMembers() does not deliver private fields of base types.

`foreach (var member in typeWrapper.UnderlyingType.GetMembers(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public))`

To solve this issue I iterate through the base types as well and I introduced a member wrapper cache which improves the serialization/deserialisation performance.
You find the modified serializer source code attached.
[YAXSerializer.cs.txt](https://github.com/YAXLib/YAXLib/files/49747/YAXSerializer.cs.txt)

Thanks in advance,
Bernhard

**Comment by axunonb** [comment]
The diff from the file submitted by Bernhard and the current version as of Dec 2, 2015:
https://www.diffchecker.com/GaQXmlkE

**Comment by axunonb** [comment]
In this context also add option to allow using private constructors for deserialization
