### ISSUE TITLE
Feature Request: Conditional Ignorance

### ISSUE THREAD

**Issue by sinairv** [YAXLib/YAXLib#4]
Let conditional ignorance. E.g., if a `DateTime` value is `DateTime.MinValue` do not serialize this. This could be achieved through predicates passed to attributes.

This has been discussed on CodePlex:
http://yaxlib.codeplex.com/discussions/360125

**Comment by 304NotModified** [comment]
+1

**Comment by axunonb** [comment]
Closing, because of duplicate to #84
