### ISSUE TITLE
Feature Request: indirect assignment of serialization attributes 

### ISSUE THREAD

**Issue by sinairv** [YAXLib/YAXLib#5]
Indirect assigning attributes to fields that we don't have access to, or we don't want to alter their source code. It is very useful for example for customized serialization of parts of the .NET framework or other class libraries which we don't have access to their source code.

This has been discussed on CodePlex:
http://yaxlib.codeplex.com/discussions/358764

**Comment by axunonb** [comment]
- The [discussion on codeplex](http://yaxlib.codeplex.com/discussions/358764) is not accessible any more.
- From the posts in this issues I would assume this could be achieved by a custom serializer, also with separation of concerns in mind . But I may be wrong.
- Should we keep this issue open?

**Comment by 304NotModified** [comment]
This is inactive for almost 9 years. Let's close this one. If others need this, they should open a new issue
