### ISSUE TITLE
Dictionary with GenericClass value serialized as an Attribute: deserializes value as Null

### ISSUE THREAD

**Issue by gigios** [YAXLib/YAXLib#50]
I have tried to serialize a dictionary with generic class as values. I want to serialize the values as attributes of each element of the dictionary.
The serialization seems working in the correct way, this is my serialization file:
```xml
<DictionaryValueGenericClassAsAttribute>
 <!-- Values are serialized as attributes of dictionary item. -->
  <Values>
    <Entry key="0" Value="10" DefaultValue="100" />
    <Entry key="1" Value="11" DefaultValue="101" />
    <Entry key="2" Value="12" DefaultValue="102" />
    <Entry key="3" Value="13" DefaultValue="103" />
    <Entry key="4" Value="14" DefaultValue="104" />
  </Values>
</DictionaryValueGenericClassAsAttribute>
```

The problem is the deserialization because it's impossible to deserialize the values of the dictionary (I obtain null values).

**Is it a my wrong management or is it impossible to manage this 'configuration' ?**

This is the class used in the DemoApplication:

```C#
using System;
using System.Collections.Generic;
using YAXLib;
namespace YAXLibTests.SampleClasses
{
    [ShowInDemoApplication]
    public class DictionaryValueGenericClassAsAttribute
    {
        [YAXComment("Values are serialized as attributes of dictionary item.")]
        [YAXErrorIfMissed(YAXExceptionTypes.Ignore)]
        [YAXDictionary(EachPairName = "Entry", KeyName = "key", SerializeKeyAs = YAXNodeTypes.Attribute, SerializeValueAs = YAXNodeTypes.Attribute)]
        public Dictionary<int, GenericValue<int>> Values { get; set; }


    public DictionaryValueGenericClassAsAttribute()
    {
        Values = new Dictionary<int, GenericValue<int>>();
    }

    public override string ToString()
    {
        return GeneralToStringProvider.GeneralToString(this);
    }

    public static DictionaryValueGenericClassAsAttribute GetSampleInstance()
    {
        var test = new DictionaryValueGenericClassAsAttribute();

        for (int i = 0; i < 5; i++)
        {
            test.Values.Add(i, new GenericValue<int> { Value = 10 + i, DefaultValue = 100 + i });
        }

        return test;
    }
}
```
```C#
public class GenericValue<T> where T : IComparable<T>
{
    [YAXAttributeFor("..")]
    [YAXErrorIfMissed(YAXExceptionTypes.Error)]
    public T Value { get; set; }

    [YAXAttributeFor("..")]
    [YAXErrorIfMissed(YAXExceptionTypes.Ignore)]
    public T DefaultValue { get; set; }
}

```

**Comment by axunonb** [comment]
Confirmed undesired behavior. Working sample attached.
[YAXLib_Issue_50.zip](https://github.com/YAXLib/YAXLib/files/6137227/YAXLib_Issue_50.zip)

**Comment by axunonb** [comment]
This boils down to certain issues ([limitations](https://www.w3.org/TR/xml/)?) with attributes. `null` for attributes is another such case (see #34).
If `[YAXAttributeFor("..")]` in `class GenericValue<T>` is omitted serialization/de-serialization works.
Looks like we have a couple of cases which are not implemented **or** cannot be implemented for attributes.

**Comment by axunonb** [comment]
If `[YAXAttributeFor("..")]` in `class GenericValue<T>` is omitted serialization/de-serialization works.

**Comment by axunonb** [comment]
@304NotModified @NKnusperer 
Some thoughts on this issue. Do you agree?
<hr/>

**1. Serialization**

The `XML` output from serialization reflects what is written in code.

**2. De-serialization**

The `XML` result coming from serialization cannot be de-serialized to the original `Dictionary<int, GenericValue<int>>`. While the `Key` of the dictionary can be identified, the `Value` as generic class cannot: The serializer "sees" the properties of `GenericValue<int>` as attributes, but there is no indication that the `Value` should become an instance of `GenericValue<int>`.

**3. Conclusion**

It is possible, that under certain conditions result of a serialization cannot be used for de-serialization.

This is not a bug. The issue should be closed.

**4. Code for this example, that allows for de-serialization of serialized XML**

```Csharp
public class DictionaryValueGenericClassAsAttribute
{
    [YAXErrorIfMissed(YAXExceptionTypes.Ignore)]
    [YAXDictionary(EachPairName = "Entry", KeyName = "DictKey", ValueName = "DictValue", SerializeKeyAs = YAXNodeTypes.Attribute,
        SerializeValueAs = YAXNodeTypes.Element)]
    public Dictionary<int, GenericValue<int>> Values { get; set; }
}

public class GenericValue<T> where T : IComparable<T>
{
    [YAXAttributeForClass]
    [YAXErrorIfMissed(YAXExceptionTypes.Error)]
    public T Value { get; set; }

    [YAXAttributeForClass]
    [YAXErrorIfMissed(YAXExceptionTypes.Ignore)]
    public T DefaultValue { get; set; }
}
```
Serialized:
```XML
<DictionaryValueGenericClassAsAttribute>
  <Values>
    <Entry DictKey="0">
      <DictValue Value="10" DefaultValue="100" />
    </Entry>
    <Entry DictKey="1">
      <DictValue Value="11" DefaultValue="101" />
    </Entry>
    <Entry DictKey="2">
      <DictValue Value="12" DefaultValue="102" />
    </Entry>
    <Entry DictKey="3">
      <DictValue Value="13" DefaultValue="103" />
    </Entry>
    <Entry DictKey="4">
      <DictValue Value="14" DefaultValue="104" />
    </Entry>
  </Values>
</DictionaryValueGenericClassAsAttribute>
```
