### ISSUE TITLE
Follow Semver standard

### ISSUE THREAD

**Issue by 304NotModified** [YAXLib/YAXLib#59]
Any plans to follow the semver standard?

http://semver.org

**Comment by sinairv** [comment]
Probably starting with 3.0 it'll be a good time to stick with semver.
It wouldn't be quite right if I say I've been following semantic versioning so far, however almost all new releases contained a new feature, and new releases within a same major version were backward compatible.

**Comment by 304NotModified** [comment]
That would be nice, but is there a 3.0 planned? 
https://github.com/sinairv/YAXLib/issues/14#issuecomment-172291746

**Comment by sinairv** [comment]
There are a lot of nice to have (breaking) changes that I can think of that can fit into a 3.0 version. These are some: 
* Removing excessive `YAX` prefix from all attributes, exceptions, etc, while there's a namespace.
* Providing a fluent syntax for defining serialization style for classes/types we don't have access to their source code (such as .NET Framework classes and 3rd party libraries).
* Code is not in a good shape. Cyclomatic complexity is high at places, while different behaviours could be defined through polymorphic objects.
* I was even thinking of renaming it from YAXLib to Yax or any other better name.

**Comment by 304NotModified** [comment]
Agree there are some nice opportunities. 

But you have stated:

> Given the relatively small number of people using the library and other available options in the .NET Framework, I was thinking it may not be worth investing more time and energy developing v3.

Is that still the case? 

semver could be applied also from now. You keep you to the rules and announce you do Semver :)

**Comment by axunonb** [comment]
Will be applied with next release
