### ISSUE TITLE
Serializing Exception is take huge amount of memory

### ISSUE THREAD

**Issue by 304NotModified** [YAXLib/YAXLib#62]
As noted at 

and seen in the `SerializeExceptionShouldNotThrowExceptions` test:

![image](https://cloud.githubusercontent.com/assets/5808377/23189391/00d21a9e-f893-11e6-9987-17e5483bb31c.png)

exceptionSerialized is huge and seems to contain ALL types in the appdomain/assembly serialized!

![image](https://cloud.githubusercontent.com/assets/5808377/23189396/04a9a20e-f893-11e6-9f9d-218eb3c8f8c5.png)

it broke my VS and xUnit while testing

it was quick-fixed with 
`ser.MaxRecursion = 10;` [See change](https://github.com/sinairv/YAXLib/pull/57/files#diff-c1cd51b68e794a8b95795b498f5052bdR2201)

But that's a quick fix ;)

This is probably also https://github.com/sinairv/YAXLib/issues/22

**Comment by sinairv** [comment]
I suggest creating a KnownType for an exception e.g., ExceptionKnownType in which we can selectively decide what to serialize (Message, StackTrace, InnerExceptions, etc), and ignore the rest (that have cyclic or deep hierarchical references).

**Comment by 304NotModified** [comment]
sounds good to me :)

**Comment by 304NotModified** [comment]
Could I also make a knowntype with a blacklist instead of whitelist? And does the knowntype work for sub classes? (e.g. knowntype on Exception, should work ook ArgumentException)

**Comment by sinairv** [comment]
I don't quite get what you mean by a blacklist known-type. 
A child of known-type is not a known-type: https://github.com/sinairv/YAXLib/blob/master/YAXLib/KnownTypes.cs#L60

So it seems my suggested work-around for treating exceptions as known-types wouldn't work :(

**Comment by 304NotModified** [comment]
Result with max recursion 10:

(8 mb) 

[exception-max-recurssion10.xml.txt](https://github.com/YAXLib/YAXLib/files/6185220/exception-max-recurssion10.xml.txt)

**Comment by axunonb** [comment]
@NKnusperer Do you think you take over this issue on the way to v3?

**Comment by NKnusperer** [comment]
Sure, will take a look at it next week.

**Comment by axunonb** [comment]
@NKnusperer Did you find the time to have a closer look on this issue?

**Comment by axunonb** [comment]
Closed with #152

**Comment by 304NotModified** [comment]
Great work @axunonb !
