### ISSUE TITLE
ICustomSerializer with more context info

### ISSUE THREAD

**Issue by 304NotModified** [YAXLib/YAXLib#72]
In our case `ICustomSerializer` is too limited to write good custom serializers. We are missing some context info. 

Would a PR accepted with a new interface so we could get more context info? I will make sure that `ICustomSerializer` still works (just with with a wrapper) and that it will be 100% backwards-compatible :)

**Comment by sinairv** [comment]
I'd like to know more about what kind of context is missing in the existing `ICustomSerializer`. However my personal preference would be if enhancing the existing one leads to a breaking change, then I'd prefer the new interface to inherit from the old `ICustomSerializer`. If that's also not possible for the design you have in mind, then let's make the new interface completely independent.

**Comment by 304NotModified** [comment]
Closing this as it's not needed for me anymore
