### ISSUE TITLE
How to display dynamic YAXSerializeAs value

### ISSUE THREAD

**Issue by newbird07** [YAXLib/YAXLib#77]
Hi 
I want to display XML like below. i dont know how to display child0 and child1 using YAXLib. kindly guide  me  
<child0 name="Unit1" key=""   ......    </child0
Class 

[YAXCollection(YAXCollectionSerializationTypes.Recursive,
                   EachElementName = "{Child}count")]
            public CustomList<Child> Child { get; set; }

**Comment by axunonb** [comment]
@newbird07: It's been a while since you asked that question. There is an example for your use case [in the wiki](https://github.com/YAXLib/YAXLib/wiki#h3formatcol). Did/does this help, so we can close the issue?

**Comment by axunonb** [comment]
Closed due to lack of activity.
