### ISSUE TITLE
Boolean serialisation

### ISSUE THREAD

**Issue by danpowell88** [YAXLib/YAXLib#78]
It appears boolean values are being serialised to "True" and "False"

according to the[ xml spec](https://www.w3.org/TR/xmlschema-2/#boolean) this is not valid

> 3.2.2.1 Lexical representation
> 
> An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}.

I think this probably stems from an object.ToString() call (which for a boolean calls Boolean.ToString() which returns the invalid value).

The default .net serialiser does not support the "True", "False" values so it would be good to maintain compatibility with this.

http://stackoverflow.com/questions/491334/why-does-boolean-tostring-output-true-and-not-true

**Comment by danpowell88** [comment]
Looks like XMLUtils.ToXmlValue could be modified with an addtional case

```
case "Boolean":
                return XmlConvert.ToString((bool) self);
```

This does break some of the existing tests that are using the uppercase booleans however

**Comment by superoctave2** [comment]
I've noticed this as well; it causes problems when the XML emitted by YAXLib has to go through a validator.    Would you accept a patch for this issue if one was submitted or do you consider the existing behavior intended/desirable?

**Comment by 304NotModified** [comment]
@axunonb  @NKnusperer  I think this should be fixed for V3, do you agree?

Should we make it an option to fallback to the old (incorrect) Pascal cased boolean values (True, False)

**Comment by axunonb** [comment]
> Should we make it an option to fallback to the old (incorrect) Pascal cased boolean values (True, False)

Make deserializing Pascal cased booleans work, but for serializing follow the xml specs now?

**Comment by NKnusperer** [comment]
Like @axunonb said we should preserve backwards compatibility by supporting deserializing pascal case and serialize correctly.
