### ISSUE TITLE
RecursiveWithNoContainingElement does not works well

### ISSUE THREAD

**Issue by xjfnet** [YAXLib/YAXLib#79]
# Example1 works well
C# code
```csharp
public class Root
{
	[YAXCollection(YAXCollectionSerializationTypes.RecursiveWithNoContainingElement)]	
	public Node[] Nodes { get; set; }
}

public class Node
{
	[YAXAttributeForClass]
	public string Name { get; set;}

	[YAXCollection(YAXCollectionSerializationTypes.RecursiveWithNoContainingElement)]	
	public Node[] Nodes { get; set; }

}
```
xml
```xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<Root>
	<Node Name="1">
		<Node Name="1a"></Node>
		<Node Name="1b"></Node>
	</Node>
	<Node Name="2">
		<Node Name="2a"></Node>
		<Node Name="2b"></Node>
	</Node>
</Root>
```
Deserialize
![2](https://cloud.githubusercontent.com/assets/4667005/25580754/fee7e9f8-2eb5-11e7-9620-31e3fada9889.png)

# Example2 dost not works well
![3](https://cloud.githubusercontent.com/assets/4667005/25581251/5c63e926-2eb9-11e7-8f5f-59abbed09892.png)

![4](https://cloud.githubusercontent.com/assets/4667005/25581314/b3f3db7e-2eb9-11e7-8ca1-819ba7bef3a3.png)
Deserialize
![5](https://cloud.githubusercontent.com/assets/4667005/25581344/d897396c-2eb9-11e7-8b1e-73105137cdf5.png)

**Comment by axunonb** [comment]
Cannot reproduce XML of serialization from 2nd example. For YAXLib v2.15 it is
```XML
<root>
  <Node name="1a" />
  <Node name="1b" />
</root>
```
For example 1 it is
```XML
<Root>
  <Node Name="1a" />
  <Node Name="1b" />
</Root1>
```
Working solution attached.
[YAXLib_Issue_79.zip](https://github.com/YAXLib/YAXLib/files/6137136/YAXLib_Issue_79.zip)

**Comment by axunonb** [comment]
Closed due to lack of activity. Issue cannot be reproduced.
