### ISSUE TITLE
Serializing types with object members has unreliable behaviour

### ISSUE THREAD

**Issue by biltongza** [YAXLib/YAXLib#82]
Suppose I have this class which captures audit information:

    public class InterceptedData
    {
        public InterceptedData()
        {
            Children = new List<InterceptedData>();
            Parameters = new List<Parameter>();
        }
        /// <summary>
        /// Method (operation) name that was invoked.
        /// </summary>
        public string MethodName { get; set; }
        
        /// <summary>
        /// Parameters that were passed to the operation.
        /// </summary>
        public List<Parameter> Parameters { get; set; }

        /// <summary>
        /// Gets or sets the return value.
        /// </summary>
        public object ReturnValue { get; set; }
        /// <summary>
        /// Additional audits that were triggered by this operation.
        /// </summary>
        public List<InterceptedData> Children { get; set; }
        /// <summary>
        /// Exception object, if an exception was thrown by the operation.
        /// </summary>
        public ExceptionDetails Exception { get; set; }
    }

My `ReturnValue` needs to be object because it can contain the return value of anything. At runtime, in one instance I am getting a List<> object back from one of my intercepted methods, and Yaxlib is serializing it like this: 

    <Value yaxlib:realtype="System.Collections.Generic.List`1[[ApplicationProcessingService.Entities.ExternalSystemMappingElement, ApplicationProcessingService.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]" />

This isn't very useful at all.

However, within my `Parameter` class which is used for the `Parameters` property, which is defined like this:

    public class Parameter
    {
        public string Name { get; set; }
        public string Type { get; set; }
        public object Value { get; set; }
    }

The values in the `Value` property of this class are serialized properly:

    <Parameters>
        <Parameter>
          <Name>eform</Name>
          <Type>ApplicationProcessingService.Entities.Eform</Type>
          <Value yaxlib:realtype="ApplicationProcessingService.Entities.Eform">
               ...
          </Value>
        </Parameter>
    </Parameters>

Why does using `object` in my `Parameter` class result in the serialization of the entire object, while the `ReturnValue` property doesn't work at all?

I don't need to deserialize any of this data, it is intended to be human readable only.

**Comment by sinairv** [comment]
Why do you think what has been serialized for `ReturnValue` isn't useful? Is the collection not empty but serialized as empty?

**Comment by biltongza** [comment]
The collection is not empty, and when it is serialized, it turns into this:
    
    <Value yaxlib:realtype="System.Collections.Generic.List`1[[ApplicationProcessingService.Entities.ExternalSystemMappingElement, ApplicationProcessingService.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]" />

You can't even deserialize that. It has no values within it, nothing. It's a self closing tag.

As a workaround, we implemented a property next to `Value` called `Items` that figures out if `Value` is a collection and returns an array of the items in the collections as the getter.

**Comment by axunonb** [comment]
@304NotModified @NKnusperer The feature implementation would be to test any `object` for `is IList` and `is IDictionary` and cast before serialization. Do you agree?

**Comment by 304NotModified** [comment]
Sounds good, but we aware that testing generic dictionaries/lists could eat some performance

**Comment by axunonb** [comment]
For the master branch as well as the current v4 branch, serializing and deserializing a generic list, that is boxed in an `object` works.
The result is different from https://github.com/YAXLib/YAXLib/issues/82#issuecomment-326061654
```CSharp
[Test]
public void Serialize_List_Boxed_In_Object()
{
    const string expected =
        @"<Object yaxlib:realtype=""System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]"" xmlns:yaxlib=""http://www.sinairv.com/yaxlib/"">
  <String>one</String>
  <String>two</String>
  <String>three</String>
</Object>";
    object toSerialize = new List<string> { "one", "two", "three" };
    var ser = CreateSerializer<object>();
    var serialized = ser.Serialize(toSerialize);
    var deserialized = ser.Deserialize(serialized);

    Assert.That(serialized, Is.EqualTo(expected));
    deserialized.Should().BeEquivalentTo(toSerialize);
}
```
Can we close this issue?

**Comment by 304NotModified** [comment]
I think we could close it.
