### ISSUE TITLE
Feature request: Adding the "ShouldSerialize" pattern possibility in the library

### ISSUE THREAD

**Issue by gigios** [YAXLib/YAXLib#84]
I have seen an old [pull request (24)](https://github.com/sinairv/YAXLib/pull/24) related the possibility to manage the **ShouldSerialize** pattern as in the standard .NET serialization.

I think that with this feature it's very easy to manage the 'conditional' serialization of some fields related the content of other fields or specifics conditions.

**Comment by axunonb** [comment]
- See also unmerged PR https://github.com/YAXLib/YAXLib/pull/24 for a suggestion to implement
- See also this feature request https://github.com/YAXLib/YAXLib/issues/4
- Consider if a `ICustomSerializer` could resolve this issue

**Comment by axunonb** [comment]
Can be achieved either with an `IKnowType` after #202 is merged, or with an `ICustomSerializer`.
