### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by RichardSinden** [YAXLib/YAXLib#87]
Hi, this is probably not strictly an issue, but I was wondering if you were planning another release at any point? Specifically, it would be useful for me if the line number changes I did a while ago could make it into a version on Nuget.
Thanks,
Richard

**Comment by 304NotModified** [comment]
bump @sinairv

**Comment by 304NotModified** [comment]
bump @sinairv

**Comment by RichardSinden** [comment]
@304NotModified I appreciate your persistence!

**Comment by 304NotModified** [comment]
👼

**Comment by rythos42** [comment]
I was about to try to add a feature I wanted, but then noticed 5 open PRs from 2018 so I think I'm just going to live with the workarounds instead. >.<

**Comment by 304NotModified** [comment]
Superseded by https://github.com/YAXLib/YAXLib/issues/116
