### ISSUE TITLE
Feature request: Allow specifying custom serializers at runtime

### ISSUE THREAD

**Issue by biltongza** [YAXLib/YAXLib#88]
Right now it seems I have to use a `[YAXCustomSerializer]` attribute on types that I need custom serialization for. However, this doesn't suit my use case and I haven't found any other XML serializer that can do what YAXLib does.

We are using YAXLib in a CQRS application to keep an audit of what commands and queries are run. The auditing is done via interception. Basically this means that at compile time, I don't know exactly what objects I'm going to be serializing, as commands and queries can take any number of parameters and could return anything as well. When the interception ocurrs, the auditing layer wraps whatever it serializes into an object that looks like this:

    /// <summary>
    /// Contains information about an operation that has taken place in the system.
    /// </summary>
    public class InterceptedData
    {
        public InterceptedData()
        {
            Children = new List<InterceptedData>();
            Parameters = new List<Parameter>();
        }
        /// <summary>
        /// Method (operation) name that was invoked.
        /// </summary>
        public string MethodName { get; set; }

        /// <summary>
        /// Parameters that were passed to the operation.
        /// </summary>
        public List<Parameter> Parameters { get; set; }

        /// <summary>
        /// Gets or sets the return value.
        /// </summary>
        public ReturnValue ReturnValue { get; set; }

        /// <summary>
        /// Additional audits that were triggered by this operation.
        /// </summary>
        public List<InterceptedData> Children { get; set; }

        /// <summary>
        /// Exception object, if an exception was thrown by the operation.
        /// </summary>
        public ExceptionDetails Exception { get; set; }
    }

Where `Parameter` looks like this:

    public class Parameter
    {
        public string Name { get; set; }

        public string Type { get; set; }

        public object Value { get; set; }
    }
And `ReturnValue` looks like this:

    public class ReturnValue
    {
        private readonly object value;

        public ReturnValue(object value)
        {
            this.value = value;
        }

        public object Value
        {
            get
            {
                if(this.value is byte[])
                {
                    return Convert.ToBase64String(this.value as byte[]);
                }
                return this.value;
            }
        }

        public object[] Items
        {
            get
            {
                if(value is string || value is byte[])
                {
                    return null;
                }
                if (value.GetType().GetInterface(typeof(IEnumerable).FullName) != null)
                {
                    return (object[])value.GetType().GetMethod("ToArray").Invoke(value, new object[] { });
                }

                return null;
            }
        }
    }

So as you can see, anything can be put into these `Parameter` and `ReturnValue` objects. YAX has done very well with this, where other serializers have either thrown errors at runtime about unknown types, or just skipped those members when encountering them.

My biggest issue is with byte arrays, because YAX serializes those with a single element per byte, like so:

    <Document>
          <Byte>80</Byte>
          <Byte>75</Byte>
          <Byte>3</Byte>
          <Byte>4</Byte>
          ....
    </Document>

This takes up a lot of space, so we want to base64 encode any byte arrays the serializer encounters. I did some reading up and I see that YAX does supply an interface to provide custom serialization, so I wrote this quick and dirty custom serializer:

    public class ByteArraySerialzer : ICustomSerializer<byte[]>
    {
        public byte[] DeserializeFromAttribute(XAttribute attrib)
        {
            return Convert.FromBase64String(attrib.Value);
        }

        public byte[] DeserializeFromElement(XElement element)
        {
            return Convert.FromBase64String(element.Value);
        }

        public byte[] DeserializeFromValue(string value)
        {
            return Convert.FromBase64String(value);
        }

        public void SerializeToAttribute(byte[] objectToSerialize, XAttribute attrToFill)
        {
            attrToFill.Value = Convert.ToBase64String(objectToSerialize);
        }

        public void SerializeToElement(byte[] objectToSerialize, XElement elemToFill)
        {
            elemToFill.Value = Convert.ToBase64String(objectToSerialize);
        }

        public string SerializeToValue(byte[] objectToSerialize)
        {
            return Convert.ToBase64String(objectToSerialize);
        }
    }

Now my problem is telling the serializer to use it. I can't go and stick it on my `Parameter` and `ReturnValue` members. YAX also doesn't expose any way that I can see to hook into the serialization process. Basically I'd like to be able to say "while serializing if `T` is encountered and there is a `ICustomSerializer<T>` registered, use that instead of base serialization".

I'm able to specify what custom serializers I want to be registered at the initialization stage and I should never need to change those serializers at any point in the lifetime of the serializer.

**Comment by axunonb** [comment]
Resolved with release [v4.0.0](https://github.com/YAXLib/YAXLib/releases/tag/v4.0.0)
