### ISSUE TITLE
YAXAttributeForClass attribute is ignored when a YAXCustomSerializer is defined on the property's type

### ISSUE THREAD

**Issue by rsaugier** [YAXLib/YAXLib#97]
A simple type is defined like this:

```vbnet
<YAXCustomSerializer(GetType(MyCustomSerializer))>
Public Class MyType

   Private _foo As String
   ...

End Class
```

The custom serializer MyCustomSerializer simply serializes MyType as its _foo string in all cases.

Let's define the following class "Sample", which holds a property of type 'MyType'.

```vbnet
Public Class Sample
        <YAXAttributeForClass>
        <YAXSerializeAs("attr")>
        Public Property Prop As MyType
End Class
```

If we try to serialize Sample, then the property 'Prop' is always serialized as an inner element, and not as an attribute, as specified by YAXAttributeForClass ...

The problem can be worked around by specifying the custom serializer on the property instead of the property type.

```vbnet
Public Class Sample
        <YAXAttributeForClass>
        <YAXCustomSerializer(GetType(MyCustomSerializer))>
        <YAXSerializeAs("attr")>
        Public Property Prop As MyType
End Class
```

Then YAXAttributeForClass is honoured correctly.

This looks like a bug in YAXLib to me, but I might be wrong! What do you think ?

**Comment by axunonb** [comment]
The behavior of YAXLib corresponds to the issue description, including the workaround found.
Also, the `SimpleTypeSerializer` is discovered for `Sample.Prop`, but not the `SerializeAs` attribute.

The workaround covers custom serialization for `ICustomSerializer.SerializeToElement` and `ICustomSerializer.SerializeToAttribute`, but not for `ICustomSerializer.SerializeToValue`. 

@NKnusperer I would consider this a missing piece of implementation. Your opinion?

Source to reproduce the issue:
[YAXLib_Issue_97.zip](https://github.com/YAXLib/YAXLib/files/6255327/YAXLib_Issue_97.zip)

**Comment by NKnusperer** [comment]
@axunonb I would considers this as a missing edge case too. No reason why this shouldn't work.
